### ISSUE TITLE
Validate with Schematron including xslt3

### ISSUE THREAD

**Issue by FredLanic** [AxelCourt/jing-trang#2]
Hello Axel,
As you know, we'll need, in a near future, to validate XML files with a Schematron including XSLT3 files (may be defined by @queryBuilding='xslt3' in the sch)
Could you, please, have a look to this subject and the tell me impacts you see ?
I know, it's a very new feature, 
TIA
Fred

**Comment by AxelCourt** [comment]
Hi Frédéric,

I guess changing the XSL used for Schematron compilation to output `version="3.0"` in the generated styleesheet if `@queryBinding="xslt3"` _should_ be enough. The compiled stylesheet should be XSLT 3.0 compliant, and the imported/included stylesheets would thus be treated as XSLT 3.0 by Saxon.

I guess we will have to test this thoroughly to be sure!

++
Axel

**Comment by cmarchand** [comment]
Until we do not use packages, it should be Ok as is...
Christophe

**Comment by AxelCourt** [comment]
You're right, it will be another "quick and dirty" solution pending an official and more robust XSLT 3.0 Schematron Skeleton transformation.

**Comment by AxelCourt** [comment]
I changed the `iso-schematron.xsl` transformation so that XSLT 3.0 is used when `@queryBinding = 'xslt3'`.
I then switched Saxon dependency to Saxon 9.8 HE which can execute XSLT 3.0 and messed up with some Java classes so that older Saxon versions could also be used with a PE / EE license to have XSLT 3.0 functionalities working as well.
Saxonica droped XSLT 1.0 support in Saxon 9.8 HE so I had to rewrite a lot of transformations / integration tests to manage to switch all XSLT transformations to 2.0 (except the ones used with Xalan).
Anyway, commit [`#eae10d7`](https://github.com/AxelCourt/jing-trang/commit/eae10d7ad663968fa19df424508ce35b4e0a4bf1) sould add what you required. All Ant tests passed successfully - but I hope you have lots of crazy tests ready just to be sure that I did not break anything!

**Comment by AxelCourt** [comment]
I added an inclusion resolution phase before the Schematron file validation (which is mandatory; Jing does not try to compile the Schematron if it is invalid).
We can now use `<iso:include href="pattern.sch"/>` in the Schematron files, or even `<iso:extends href="abstract.sch">` (which is not canonical btw).
If there are IDs from the imported file referenced in the main Schematron file, it no longers prevent the Schematron from being valid as inclusion resolution is made before validation.
